function HSV = RGBtoHSV(image)
image = im2double(image);
% imshow(image);
R = image(:,:,1);
G = image(:,:,2);
B = image(:,:,3);
maxRGB = max(image,[],3);
minRGB = min(image,[],3);
% maxrgbeqR = (maxRGB == R);
% modd = (mod(((60*((G-B)./(maxRGB-minRGB)))+360),360));
% modarg = (60*((G-B)./(maxRGB-minRGB)))+360;
maxIsR = (maxRGB==R & maxRGB ~= minRGB);
matr = (mod(((60*((G-B)./(maxRGB-minRGB)))+360),360));
matr(~maxIsR) = 0;
h = matr;
maxIsG = (maxRGB==G & maxRGB ~= minRGB & maxRGB ~= R);
matr = ((60*((B-R)./(maxRGB-minRGB)))+120);
matr(~maxIsG) = 0;
h = h + matr;
maxIsB = (maxRGB==B & maxRGB ~= minRGB & maxRGB ~= R & maxRGB ~= G);
matr = ((60*((R-G)./(maxRGB-minRGB)))+240);
matr(~maxIsB) = 0;
h = h + matr;

% h = ((maxRGB == minRGB) * 0) + ((maxRGB == R).*(mod(((60*((G-B)./(maxRGB-minRGB)))+360),360))) + ((maxRGB == G).*(((60*((B-R)./(maxRGB-minRGB)))+120))) + ((maxRGB == G).*(((60*((R-G)./(maxRGB-minRGB)))+240)));
% s = (maxRGB ~= 0).*(1-(minRGB./maxRGB));
maxIs0 = (maxRGB == 0);
s = (1-(minRGB./maxRGB));
s(maxIs0) = 0;
v = maxRGB;
HSV = cat(3,cat(3,h,s),v);
